### ISSUE TITLE
几个建议

### ISSUE THREAD

**Issue by RedTearsss** [Lonely-Atom/HideTaskbar#2]
1.防止进程重复运行的话，靠进程名称来判断是很不严谨的，建议通过CreateMutex和OpenMutex来判断；
2.显隐任务栏的时候不建议弹notification；
3.快捷键建议可修改，哪怕是通过ini文件来操作，Ctrl+`与某些软件的默认快捷键是有冲突的；
4.托盘菜单是可以带显隐任务栏的菜单项的，只需要在弹出菜单的时候或者显隐任务栏的时候，根据任务栏状态更新一下菜单项的状态即可，是有用的。

**Comment by RedTearsss** [comment]
5.注册热键失败，貌似没有提示和处理。

**Comment by Lonely-Atom** [comment]
好的，感谢你的建议，回头我来调整一下。

**Comment by Lonely-Atom** [comment]
感谢你的建议，我还是认为第四项是没必要的，所以没有采纳这项建议，其他几项建议都已完成。
