### ISSUE TITLE
Ctrl + Shift + 1快捷键是Win11系统默认快捷键

### ISSUE THREAD

**Issue by RedTearsss** [Lonely-Atom/HideTaskbar#4]
https://support.microsoft.com/en-us/windows/keyboard-shortcuts-in-windows-dcc61a57-8ff0-cffe-9796-cb9706c75eec#windowskey
# Ctrl + Shift + Number (1-8)  -  Changes folder view.

**Comment by Lonely-Atom** [comment]
目前可以在配置文件里修改快捷键了，默认的快捷键你有更好的推荐吗？

**Comment by Lonely-Atom** [comment]
已修改显示/隐藏系统托盘的默认快捷键为`Ctrl+Alt+~`。

**Comment by RedTearsss** [comment]
能修改快捷键了之后，默认的是啥已经没那么大影响了，找个顺手的不跟系统快捷键冲突的都可以的。

**Comment by Lonely-Atom** [comment]
是的，你提的这个Issue之前就已经加了可以在配置文件`appsettings.json`里修改快捷键了，我看你这Issue，还以为你是对默认快捷键不满意，不过确实默认快捷键跟系统快捷键冲突的话，还是修改一个比较好，就改了默认快捷键，感谢你提出的建议~

**Comment by RedTearsss** [comment]
我是不用这个快捷键的，但是看到readme里写了win11无效，就查了一下才提的issue。
默认快捷键可以跟第三方软件冲突，但是最好还是不要跟系统快捷键冲突。

**Comment by Lonely-Atom** [comment]
其实不是快捷键在win11无效，而是打开系统托盘功能在win11上无效，我尝试了去捕获系统托盘的窗口句柄，但win11应该改写了系统托盘，无法通过句柄直接打开系统托盘。
