### ISSUE TITLE
我没能解决的一些 BUG

### ISSUE THREAD

**Issue by Wwwwtgd** [Lonely-Atom/HideTaskbar#5]
首先，我感到非常抱歉，因为在我之前编写的功能中存在一些 Bug。我找了很多办法，包括一些曲线救国的方法，但我似乎没有能力解决这些问题，我想用户应当知道这些问题。如果您觉得有必要，请去除  “隐藏系统托盘” 的功能。
实际场景如下：
       1、在使用快捷键打开系统托盘后，无法通过鼠标点击其它位置实现关闭系统托盘。
       2、在使用快捷键打开系统托盘后，当系统托盘中的项目超过 9个、12个或16个时，通过快捷键打开的系统托盘的尺寸不会自动更新，也就会看不到新加入的托盘图标，目前只能通过显示出任务栏，重新手动点击展开系统托盘来更新它。
      3、在开机后，直接展开系统托盘功能无效，需要先手动展开一次系统托盘才能使用快捷键快速展开。

由于微软并没有提供或是我没能找到 更改或更新系统托盘的接口或方法，因此没能找到解决问题的方法，我迫切地想知道在鼠标点击展开系统托盘时 windows 后台到底执行了些什么操作，但它毕竟不是开源的。

同时我还有下面的一个九九：
使用 time 每 300ms 一直进行 "完全隐藏" 的操作是否浪费了资源（是否可以使用线程，让自动隐藏先执行，检测线程结束后再执行完全隐藏。）因为我之前使用 C 语言编写这个功能时发现，自动隐藏+完全隐藏才能实现全屏各种应用最好的办法，但它们没有办法连在一起执行，否则完全隐藏的操作会失效。当我看到您的代码，发现使用计时器来实现完全隐藏的功能时感到眼前一亮，我知道这个计时器对系统的影响是微乎其微的，但对于一个完美主义者来说，这难免有些难受，因为这似乎不是最完美的解决方案。当然这是非常不必要的。

最后，非常抱歉，在我添加功能时并没有经过全面的测试，使中出现了这么多 BUG，并且我还没有能力解决。真的很抱歉。

**Comment by Lonely-Atom** [comment]
别太担心，也更不必自责，你能参与到这之中来，并且提供了一些很好的建议和想法，这让我不再孤单一人，也让这个项目有了更多生命力，对我来说，这些意义更加重要。剩下的，只需要让我们一起来研究研究如何解决就好。

对于你提到的3个bug：
1. 这个问题我发现了，我认为是通过快捷键打开的，所以通过快捷键来关闭也是合理的，当然如果能实现鼠标点击其他位置自动关闭，这更加完美。
2. 这个bug，我还真的没怎么注意到过，可能我的系统托盘内的图标不够多，哈哈，我后续会来研究一下。
3. 这个bug，我也没怎么注意到，我后续也会来研究一下。

对于你所说的隐藏任务栏的完美解决方案，为什么我会使用 timer 循环执行`完全隐藏`动作，是因为我曾发现过一个bug，是在系统托盘弹出通知时，会使`完全隐藏`失效，我尝试了很多方法来监听系统托盘的通知事件，但似乎无法实现，所以使用了这样一个曲线救国的方案。接下来我也会再研究一下是否会有更好的解决方案。

如果你发现了其他解决方案或问题，也可以直接在这个Issue反馈，再次感谢你的参与~

**Comment by Lonely-Atom** [comment]
1. 通过在显示系统托盘的同时将`焦点转移`到系统托盘窗口。
    - 解决了任务栏隐藏的状态下显示系统托盘后，鼠标点击其他位置不会自动隐藏系统托盘的问题

2. 目前研究了一种更好的方法，通过使用找到任务栏句柄上的系统托盘按钮句柄上的按钮，再通过向按钮`发送点击消息`模拟点击系统托盘按钮来打开系统托盘的方法，替代了原来的直接显示/隐藏系统托盘窗口的方式。
    - 解决了任务栏隐藏的状态下显示系统托盘后，系统托盘窗口大小不自动更新的问题
    - 解决了开机自启动时自动隐藏任务栏后，显示系统托盘失效的问题

    > 我猜测通过点击系统托盘按钮的方式展开关闭系统托盘窗口会触发系统托盘的一些系统级的底层逻辑，其中包含了更新窗口大小等，所以解决了上述两个问题，但之前的直接显示系统托盘窗口的方式不会触发。

    > 但此方法带来了一些新的问题：在任务栏隐藏的状态下，通过此方法来显示系统托盘，会导致系统托盘窗口显示在屏幕的左上角（类似系统托盘无法找到任务栏作为锚点来定位）。我通过在向按钮发送点击消息之前将任务栏先显示，再发送点击消息，最后再次隐藏任务栏解决了此问题。（因为执行速度极快，所以肉眼几乎不会察觉到任务栏的回显，但无法完全规避）

    > 然后其实只解决了一部分问题，还有一种情况，就是在系统托盘出现一些更新时的第一次会出现相同的问题，应该也是系统托盘无法找到任务栏作为锚点来定位（比如系统托盘中的某个图标的程序其实已经退出，但图标还未消失，当鼠标放到图标上时，系统托盘会将其更新掉），但此问题无法监听捕获，所以暂时也无法解决（我认为这也属于实在是无法解决的系统级底层问题，所以暂时放弃解决此问题）

3. 关于通过`Timer_Tick`每`300ms`重复执行隐藏任务栏的操作，其实不是`自动隐藏+完全隐藏`没办法连在一起执行，而是我之前发现出现通知时会导致隐藏失效，而我找了很多办法想监听通知来重新触发隐藏，但找不到方法监听，所以使用了此下策，但对系统运行影响应该很小。

**Comment by Lonely-Atom** [comment]
我昨晚又尝试了一下在Win11系统上使用新方式，但似乎也还是不起效，我猜测Win11的系统托盘按钮做了一些新的设计，我们无法通过发送点击消息来使其工作。

**Comment by Wwwwtgd** [comment]
大佬好强，解决了我之前的那么多问题。
通过阅读您的代码，我又知道了一个好玩的工具 “winspy++”，感谢推荐。

您使用了获取 "Shell_TrayWnd" 的子句柄 "TrayNotifyWnd" 上的按钮发送点击事件的方法来实现，这是我之前没有想到的，我之前只是粗暴地使用 ShowWindows 去尝试将 "TrayNotifyWnd" 显现出来 。
关于 win11系统托盘无效 的问题
我目前知道的是在 win10 中
系统托盘的句柄类名是 “NotifyIconOverflowWindow” 
句柄号是 65906 
进程id是 11060
父类句柄号是 65552  即 “Shell_TrayWnd“

而我在朋友的 win11 上查看到的
系统托盘句柄类名是  “TopLevelWindowForOverflowXamlIsland” 
句柄号是 958746
进程id是 9524
父类句柄是 65552 在win11中也是 “Shell_TrayWnd“

我知道新方法似乎用不到这些，但还是希望能够帮助到你，并且我也会寻找解决办法。

**Comment by RedTearsss** [comment]
关于Win11的托盘区，大概研究了一下，给点思路吧，C# 不太熟悉搞不了。
直接去操作TopLevelWindowForOverflowXamlIsland是没有用的，貌似是与“显示隐藏的图标”按钮的状态相关联，按钮处于关闭托盘区的状态下，是显示不出来TopLevelWindowForOverflowXamlIsland的，按钮处于打开托盘区的状态下，是可以随意的显示隐藏TopLevelWindowForOverflowXamlIsland的。
Windows.UI.Input.InputSite.WindowClass还是win32控件，可以获取到句柄，下边的控件好像是UI Automation控件，WPF用的XAML那种，就获取不到了的，因为没有句柄，可能需要用类似
```
GetWindow(handle,GW_Child);
GetWindow(handle,GW_HWNDNEXT);
```
这样的方式去取到“显示隐藏的图标”按钮的相关的ID类似的属性，然后去触发即可。
```
ClassName:Shell_TrayWnd
    ClassName:Windows.UI.Composition.DesktopWindowContentBridge
        ClassName:Windows.UI.Input.InputSite.WindowClass
            ClassName:Taskbar.TaskbarFrameAutomationPeer
            ClassName:SystemTray.NormalButton	//UIA_Button:显示隐藏的图标
```
